/* Generated By:JavaCC: Do not edit this line. OLParserTreeConstants.java Version 5.0 */
package org.yamcs.scos2k.ol;

public interface OLParserTreeConstants
{
  public int JJTFORMULA = 0;
  public int JJTSTATEMENT = 1;
  public int JJTCONDITIONALSTATEMENT = 2;
  public int JJTSTATEMENTLIST = 3;
  public int JJTEXPRESSIONSTATEMENT = 4;
  public int JJTASSIGNMENTSTATEMENT = 5;
  public int JJTEXPRESSION = 6;
  public int JJTLOGICALEXPRESSION = 7;
  public int JJTSHIFTEXPRESSION = 8;
  public int JJTRELATIONLEXPRESSION = 9;
  public int JJTADDITIVEEXPRESSION = 10;
  public int JJTMULTIPLICATIVEEXPRESSION = 11;
  public int JJTUNARYEXPRESSION = 12;
  public int JJTPRIMARYEXPRESSION = 13;
  public int JJTARGUMENTLIST = 14;
  public int JJTFUNCTIONNAME = 15;
  public int JJTCONSTANT = 16;
  public int JJTRELOP = 17;
  public int JJTLOGICOP1 = 18;
  public int JJTSHIFTOP = 19;
  public int JJTADDOP = 20;
  public int JJTMULOP = 21;
  public int JJTLOGICOP = 22;


  public String[] jjtNodeName = {
    "FORMULA",
    "Statement",
    "ConditionalStatement",
    "StatementList",
    "ExpressionStatement",
    "AssignmentStatement",
    "Expression",
    "LogicalExpression",
    "ShiftExpression",
    "RelationlExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "PrimaryExpression",
    "ArgumentList",
    "FunctionName",
    "Constant",
    "RelOp",
    "LogicOp1",
    "ShiftOp",
    "AddOp",
    "MulOp",
    "LogicOp",
  };
}
/* JavaCC - OriginalChecksum=84d0f797cbeb4dd0cb4193e563d44a24 (do not edit this line) */
